SKILL_DATABASE = {   'Acrobatics': {   'attr': 'Strength',
                      'cost': 75,
                      'min': 0,
                      'name': 'Acrobatics',
                      'parent': None,
                      'prereq': []},
    'Acrobatics_Dodge': {   'attr': 'Agility',
                            'cost': 100,
                            'min': 17,
                            'name': 'Spry',
                            'parent': 'Acrobatics',
                            'prereq': []},
    'Acrobatics_Jump': {   'attr': 'Strength',
                           'cost': 100,
                           'min': 17,
                           'name': 'Jump',
                           'parent': 'Acrobatics',
                           'prereq': []},
    'Acrobatics_SwiftReflexes': {   'attr': 'Agility',
                                    'cost': 0,
                                    'min': 17,
                                    'name': 'Swift Reflexes',
                                    'parent': 'Acrobatics',
                                    'prereq': []},
    'Acrobatics_Tumble': {   'attr': 'Agility',
                             'cost': 150,
                             'min': 23,
                             'name': 'Tumble',
                             'parent': 'Acrobatics',
                             'prereq': ['Tactics_Juke']},
    'Axe': {   'attr': 'Strength',
               'cost': 50,
               'min': 0,
               'name': 'Axe',
               'parent': None,
               'prereq': []},
    'Axe_Berserk': {   'attr': 'Strength',
                       'cost': 300,
                       'min': 29,
                       'name': 'Berserk!',
                       'parent': 'Axe',
                       'prereq': ['Axe_Dismember']},
    'Axe_Cleave': {   'attr': 'Strength',
                      'cost': 150,
                      'min': 19,
                      'name': 'Cleave',
                      'parent': 'Axe',
                      'prereq': []},
    'Axe_Decapitate': {   'attr': 'Strength',
                          'cost': 150,
                          'min': 25,
                          'name': 'Decapitate',
                          'parent': 'Axe',
                          'prereq': ['Axe_Dismember']},
    'Axe_Dismember': {   'attr': 'Strength',
                         'cost': 150,
                         'min': 21,
                         'name': 'Dismember',
                         'parent': 'Axe',
                         'prereq': []},
    'Axe_Expertise': {   'attr': 'Strength',
                         'cost': 0,
                         'min': 0,
                         'name': 'Axe Proficiency',
                         'parent': 'Axe',
                         'prereq': []},
    'Axe_HookAndDrag': {   'attr': 'Strength',
                           'cost': 150,
                           'min': 23,
                           'name': 'Hook and Drag',
                           'parent': 'Axe',
                           'prereq': []},
    'CookingAndGathering': {   'attr': 'Intelligence',
                               'cost': 100,
                               'min': 0,
                               'name': 'Cooking and Gathering',
                               'parent': None,
                               'prereq': []},
    'CookingAndGathering_Butchery': {   'attr': 'Intelligence',
                                        'cost': 50,
                                        'min': 15,
                                        'name': 'Butchery',
                                        'parent': 'CookingAndGathering',
                                        'prereq': []},
    'CookingAndGathering_CarbideChef': {   'attr': 'Intelligence',
                                           'cost': 100,
                                           'min': 17,
                                           'name': 'Carbide Chef',
                                           'parent': 'CookingAndGathering',
                                           'prereq': []},
    'CookingAndGathering_Harvestry': {   'attr': 'Intelligence',
                                         'cost': 50,
                                         'min': 15,
                                         'name': 'Harvestry',
                                         'parent': 'CookingAndGathering',
                                         'prereq': []},
    'CookingAndGathering_MealPreparation': {   'attr': 'Intelligence',
                                               'cost': 0,
                                               'min': 15,
                                               'name': 'Meal Preparation',
                                               'parent': 'CookingAndGathering',
                                               'prereq': []},
    'CookingAndGathering_Spicer': {   'attr': 'Intelligence',
                                      'cost': 50,
                                      'min': 17,
                                      'name': 'Spicer',
                                      'parent': 'CookingAndGathering',
                                      'prereq': []},
    'Cudgel': {   'attr': 'Strength',
                  'cost': 50,
                  'min': 0,
                  'name': 'Cudgel',
                  'parent': None,
                  'prereq': []},
    'Cudgel_Backswing': {   'attr': 'Strength',
                            'cost': 100,
                            'min': 23,
                            'name': 'Backswing',
                            'parent': 'Cudgel',
                            'prereq': []},
    'Cudgel_Bludgeon': {   'attr': 'Strength',
                           'cost': 150,
                           'min': 17,
                           'name': 'Bludgeon',
                           'parent': 'Cudgel',
                           'prereq': []},
    'Cudgel_ChargingStrike': {   'attr': 'Strength',
                                 'cost': 100,
                                 'min': 19,
                                 'name': 'Charging Strike',
                                 'parent': 'Cudgel',
                                 'prereq': [   'Cudgel_Bludgeon',
                                               'Tactics_Charge']},
    'Cudgel_Conk': {   'attr': 'Strength',
                       'cost': 150,
                       'min': 21,
                       'name': 'Conk',
                       'parent': 'Cudgel',
                       'prereq': ['Cudgel_Bludgeon']},
    'Cudgel_Expertise': {   'attr': 'Strength',
                            'cost': 0,
                            'min': 0,
                            'name': 'Cudgel Proficiency',
                            'parent': 'Cudgel',
                            'prereq': []},
    'Cudgel_Slam': {   'attr': 'Strength',
                       'cost': 150,
                       'min': 25,
                       'name': 'Slam',
                       'parent': 'Cudgel',
                       'prereq': []},
    'Cudgel_SmashUp': {   'attr': 'Strength',
                          'cost': 300,
                          'min': 29,
                          'name': 'Demolish',
                          'parent': 'Cudgel',
                          'prereq': ['Cudgel_Slam']},
    'Customs': {   'attr': 'Intelligence',
                   'cost': 150,
                   'min': 0,
                   'name': 'Customs and Folklore',
                   'parent': None,
                   'prereq': []},
    'Customs_Tactful': {   'attr': 'Intelligence',
                           'cost': 0,
                           'min': 19,
                           'name': 'Tactful',
                           'parent': 'Customs',
                           'prereq': []},
    'Customs_TrashDivining': {   'attr': 'Intelligence',
                                 'cost': 150,
                                 'min': 21,
                                 'name': 'Trash Divining',
                                 'parent': 'Customs',
                                 'prereq': []},
    'Discipline': {   'attr': 'Willpower',
                      'cost': 150,
                      'min': 0,
                      'name': 'Self-discipline',
                      'parent': None,
                      'prereq': []},
    'Discipline_Conatus': {   'attr': 'Willpower',
                              'cost': 150,
                              'min': 23,
                              'name': 'Conatus',
                              'parent': 'Discipline',
                              'prereq': []},
    'Discipline_FastingWay': {   'attr': 'Willpower',
                                 'cost': 50,
                                 'min': 17,
                                 'name': 'Fasting Way',
                                 'parent': 'Discipline',
                                 'prereq': []},
    'Discipline_IronMind': {   'attr': 'Willpower',
                               'cost': 100,
                               'min': 21,
                               'name': 'Iron Mind',
                               'parent': 'Discipline',
                               'prereq': []},
    'Discipline_Lionheart': {   'attr': 'Willpower',
                                'cost': 100,
                                'min': 21,
                                'name': 'Lionheart',
                                'parent': 'Discipline',
                                'prereq': []},
    'Discipline_Meditate': {   'attr': 'Willpower',
                               'cost': 0,
                               'min': 0,
                               'name': 'Meditate',
                               'parent': 'Discipline',
                               'prereq': []},
    'Discipline_MindOverBody': {   'attr': 'Willpower',
                                   'cost': 150,
                                   'min': 29,
                                   'name': 'Mind over Body',
                                   'parent': 'Discipline',
                                   'prereq': []},
    'Endurance': {   'attr': 'Toughness',
                     'cost': 100,
                     'min': 0,
                     'name': 'Endurance',
                     'parent': None,
                     'prereq': []},
    'Endurance_Calloused': {   'attr': 'Toughness',
                               'cost': 200,
                               'min': 23,
                               'name': 'Calloused',
                               'parent': 'Endurance',
                               'prereq': []},
    'Endurance_Juicer': {   'attr': 'Toughness',
                            'cost': 150,
                            'min': 23,
                            'name': 'Juicer',
                            'parent': 'Endurance',
                            'prereq': []},
    'Endurance_Longstrider': {   'attr': 'Toughness',
                                 'cost': 250,
                                 'min': 25,
                                 'name': 'Longstrider',
                                 'parent': 'Endurance',
                                 'prereq': []},
    'Endurance_PoisonTolerance': {   'attr': 'Toughness',
                                     'cost': 100,
                                     'min': 19,
                                     'name': 'Poison Tolerance',
                                     'parent': 'Endurance',
                                     'prereq': []},
    'Endurance_ShakeItOff': {   'attr': 'Toughness',
                                'cost': 0,
                                'min': 0,
                                'name': 'Shake It Off',
                                'parent': 'Endurance',
                                'prereq': []},
    'Endurance_Swimming': {   'attr': 'Toughness',
                              'cost': 100,
                              'min': 15,
                              'name': 'Swimming',
                              'parent': 'Endurance',
                              'prereq': []},
    'Endurance_Weathered': {   'attr': 'Toughness',
                               'cost': 200,
                               'min': 21,
                               'name': 'Weathered',
                               'parent': 'Endurance',
                               'prereq': []},
    'HeavyWeapons': {   'attr': 'Strength',
                        'cost': 100,
                        'min': 0,
                        'name': 'Heavy Weapon',
                        'parent': None,
                        'prereq': []},
    'HeavyWeapons_StrappingShoulders': {   'attr': 'Strength',
                                           'cost': 0,
                                           'min': 19,
                                           'name': 'Strapping Shoulders',
                                           'parent': 'HeavyWeapons',
                                           'prereq': []},
    'HeavyWeapons_Sweep': {   'attr': 'Strength',
                              'cost': 200,
                              'min': 27,
                              'name': 'Sweep',
                              'parent': 'HeavyWeapons',
                              'prereq': []},
    'HeavyWeapons_Tank': {   'attr': 'Strength',
                             'cost': 150,
                             'min': 23,
                             'name': 'Tank',
                             'parent': 'HeavyWeapons',
                             'prereq': []},
    'LongBlades': {   'attr': 'Agility',
                      'cost': 100,
                      'min': 0,
                      'name': 'Long Blade',
                      'parent': None,
                      'prereq': []},
    'LongBladesDeathblow': {   'attr': 'Strength,Agility|Agility,Strength',
                               'cost': 300,
                               'min': 29,
                               'name': 'En Garde!',
                               'parent': 'LongBlades',
                               'prereq': []},
    'LongBladesDuelingStance': {   'attr': 'Intelligence',
                                   'cost': 200,
                                   'min': 17,
                                   'name': 'Dueling Stance',
                                   'parent': 'LongBlades',
                                   'prereq': []},
    'LongBladesImprovedAggressiveStance': {   'attr': 'Strength',
                                              'cost': 100,
                                              'min': 23,
                                              'name': 'Improved Aggressive '
                                                      'Stance',
                                              'parent': 'LongBlades',
                                              'prereq': []},
    'LongBladesImprovedDefensiveStance': {   'attr': 'Agility',
                                             'cost': 100,
                                             'min': 23,
                                             'name': 'Improved Defensive '
                                                     'Stance',
                                             'parent': 'LongBlades',
                                             'prereq': []},
    'LongBladesImprovedDuelistStance': {   'attr': 'Intelligence',
                                           'cost': 100,
                                           'min': 21,
                                           'name': 'Improved Dueling Stance',
                                           'parent': 'LongBlades',
                                           'prereq': [   'LongBladesDuelingStance']},
    'LongBladesLunge': {   'attr': 'Agility',
                           'cost': 200,
                           'min': 17,
                           'name': 'Lunge',
                           'parent': 'LongBlades',
                           'prereq': []},
    'LongBladesProficiency': {   'attr': 'Strength',
                                 'cost': 0,
                                 'min': 0,
                                 'name': 'Long Blade Proficiency',
                                 'parent': 'LongBlades',
                                 'prereq': []},
    'LongBladesSwipe': {   'attr': 'Strength',
                           'cost': 200,
                           'min': 17,
                           'name': 'Swipe',
                           'parent': 'LongBlades',
                           'prereq': []},
    'Multiweapon_Expertise': {   'attr': 'Agility|Strength',
                                 'cost': 150,
                                 'min': 23,
                                 'name': 'Multiweapon Expertise',
                                 'parent': 'Multiweapon_Fighting',
                                 'prereq': ['Multiweapon_Proficiency']},
    'Multiweapon_Fighting': {   'attr': 'Agility',
                                'cost': 150,
                                'min': 0,
                                'name': 'Multiweapon Fighting',
                                'parent': None,
                                'prereq': []},
    'Multiweapon_Flurry': {   'attr': 'Agility|Strength',
                              'cost': 0,
                              'min': 17,
                              'name': 'Flurry',
                              'parent': 'Multiweapon_Fighting',
                              'prereq': []},
    'Multiweapon_Mastery': {   'attr': 'Agility|Strength',
                               'cost': 200,
                               'min': 27,
                               'name': 'Multiweapon Mastery',
                               'parent': 'Multiweapon_Fighting',
                               'prereq': ['Multiweapon_Expertise']},
    'Multiweapon_Proficiency': {   'attr': 'Agility|Strength',
                                   'cost': 0,
                                   'min': 17,
                                   'name': 'Multiweapon Proficiency',
                                   'parent': 'Multiweapon_Fighting',
                                   'prereq': []},
    'Nonlinearity': {   'attr': 'Ego',
                        'cost': 0,
                        'min': 0,
                        'name': 'Nonlinearity',
                        'parent': None,
                        'prereq': []},
    'Nonlinearity_Tomorrowful': {   'attr': 'Ego',
                                    'cost': 200,
                                    'min': 30,
                                    'name': 'Tomorrowful',
                                    'parent': 'Nonlinearity',
                                    'prereq': []},
    'Persuasion': {   'attr': 'Ego',
                      'cost': 100,
                      'min': 0,
                      'name': 'Persuasion',
                      'parent': None,
                      'prereq': []},
    'Persuasion_Berate': {   'attr': 'Ego',
                             'cost': 150,
                             'min': 19,
                             'name': 'Berate',
                             'parent': 'Persuasion',
                             'prereq': []},
    'Persuasion_InspiringPresence': {   'attr': 'Ego',
                                        'cost': 250,
                                        'min': 25,
                                        'name': 'Inspiring Presence',
                                        'parent': 'Persuasion',
                                        'prereq': []},
    'Persuasion_Intimidate': {   'attr': 'Ego',
                                 'cost': 200,
                                 'min': 17,
                                 'name': 'Intimidate',
                                 'parent': 'Persuasion',
                                 'prereq': []},
    'Persuasion_MenacingStare': {   'attr': 'Ego',
                                    'cost': 0,
                                    'min': 17,
                                    'name': 'Menacing Stare',
                                    'parent': 'Persuasion',
                                    'prereq': []},
    'Persuasion_Proselytize': {   'attr': 'Ego',
                                  'cost': 300,
                                  'min': 23,
                                  'name': 'Proselytize',
                                  'parent': 'Persuasion',
                                  'prereq': []},
    'Persuasion_SnakeOiler': {   'attr': 'Ego',
                                 'cost': 150,
                                 'min': 19,
                                 'name': 'Snake Oiler',
                                 'parent': 'Persuasion',
                                 'prereq': []},
    'Physic': {   'attr': 'Intelligence',
                  'cost': 50,
                  'min': 0,
                  'name': 'Physic',
                  'parent': None,
                  'prereq': []},
    'Physic_AmputateLimb': {   'attr': 'Intelligence',
                               'cost': 50,
                               'min': 23,
                               'name': 'Amputate Limb',
                               'parent': 'Physic',
                               'prereq': []},
    'Physic_Apothecary': {   'attr': 'Intelligence',
                             'cost': 100,
                             'min': 25,
                             'name': 'Apothecary',
                             'parent': 'Physic',
                             'prereq': []},
    'Physic_Nostrums': {   'attr': 'Intelligence',
                           'cost': 100,
                           'min': 21,
                           'name': 'Nostrums',
                           'parent': 'Physic',
                           'prereq': []},
    'Physic_StaunchWounds': {   'attr': 'Intelligence',
                                'cost': 0,
                                'min': 0,
                                'name': 'Staunch Wounds',
                                'parent': 'Physic',
                                'prereq': []},
    'Pistol': {   'attr': 'Agility',
                  'cost': 100,
                  'min': 0,
                  'name': 'Pistol',
                  'parent': None,
                  'prereq': []},
    'Pistol_Akimbo': {   'attr': 'Agility',
                         'cost': 150,
                         'min': 17,
                         'name': 'Akimbo',
                         'parent': 'Pistol',
                         'prereq': []},
    'Pistol_DeadShot': {   'attr': 'Agility',
                           'cost': 200,
                           'min': 25,
                           'name': 'Dead Shot',
                           'parent': 'Pistol',
                           'prereq': []},
    'Pistol_DisarmingShot': {   'attr': 'Agility',
                                'cost': 100,
                                'min': 23,
                                'name': 'Disarming Shot',
                                'parent': 'Pistol',
                                'prereq': []},
    'Pistol_EmptyTheClips': {   'attr': 'Agility',
                                'cost': 300,
                                'min': 27,
                                'name': 'Empty the Clips',
                                'parent': 'Pistol',
                                'prereq': []},
    'Pistol_FastestGun': {   'attr': 'Agility',
                             'cost': 400,
                             'min': 29,
                             'name': 'Fastest Gun in the Rust',
                             'parent': 'Pistol',
                             'prereq': []},
    'Pistol_SlingAndRun': {   'attr': 'Agility',
                              'cost': 50,
                              'min': 21,
                              'name': 'Sling and Run',
                              'parent': 'Pistol',
                              'prereq': []},
    'Pistol_SteadyHands': {   'attr': 'Agility',
                              'cost': 0,
                              'min': 0,
                              'name': 'Steady Hand',
                              'parent': 'Pistol',
                              'prereq': []},
    'Pistol_WeakSpotter': {   'attr': 'Agility',
                              'cost': 150,
                              'min': 19,
                              'name': 'Weak Spotter',
                              'parent': 'Pistol',
                              'prereq': []},
    'Rifle_BeaconFire': {   'attr': 'Agility',
                            'cost': 200,
                            'min': 25,
                            'name': 'Beacon Fire',
                            'parent': 'Rifles',
                            'prereq': ['Rifle_DrawABead', 'Rifle_SureFire']},
    'Rifle_DisorientingFire': {   'attr': 'Agility',
                                  'cost': 200,
                                  'min': 25,
                                  'name': 'Disorienting Fire',
                                  'parent': 'Rifles',
                                  'prereq': [   'Rifle_DrawABead',
                                                'Rifle_WoundingFire']},
    'Rifle_DrawABead': {   'attr': 'Agility',
                           'cost': 0,
                           'min': 19,
                           'name': 'Draw a Bead',
                           'parent': 'Rifles',
                           'prereq': []},
    'Rifle_FlatteningFire': {   'attr': 'Agility',
                                'cost': 200,
                                'min': 25,
                                'name': 'Flattening Fire',
                                'parent': 'Rifles',
                                'prereq': [   'Rifle_DrawABead',
                                              'Rifle_SuppressiveFire']},
    'Rifle_OneShot': {   'attr': 'Agility',
                         'cost': 300,
                         'min': 29,
                         'name': 'Ultra Fire',
                         'parent': 'Rifles',
                         'prereq': ['Rifle_DrawABead']},
    'Rifle_SteadyHands': {   'attr': 'Agility',
                             'cost': 0,
                             'min': 19,
                             'name': 'Steady Hands',
                             'parent': 'Rifles',
                             'prereq': []},
    'Rifle_SuppressiveFire': {   'attr': 'Agility',
                                 'cost': 150,
                                 'min': 19,
                                 'name': 'Suppressive Fire',
                                 'parent': 'Rifles',
                                 'prereq': ['Rifle_DrawABead']},
    'Rifle_SureFire': {   'attr': 'Agility',
                          'cost': 150,
                          'min': 19,
                          'name': 'Sure Fire',
                          'parent': 'Rifles',
                          'prereq': ['Rifle_DrawABead']},
    'Rifle_WoundingFire': {   'attr': 'Agility',
                              'cost': 150,
                              'min': 19,
                              'name': 'Wounding Fire',
                              'parent': 'Rifles',
                              'prereq': ['Rifle_DrawABead']},
    'Rifles': {   'attr': 'Agility',
                  'cost': 100,
                  'min': 0,
                  'name': 'Bow and Rifle',
                  'parent': None,
                  'prereq': []},
    'Shield': {   'attr': 'Strength',
                  'cost': 100,
                  'min': 0,
                  'name': 'Shield',
                  'parent': None,
                  'prereq': []},
    'Shield_Block': {   'attr': 'Strength',
                        'cost': 0,
                        'min': 0,
                        'name': 'Block',
                        'parent': 'Shield',
                        'prereq': []},
    'Shield_DeftBlocking': {   'attr': 'Agility',
                               'cost': 200,
                               'min': 19,
                               'name': 'Deft Blocking',
                               'parent': 'Shield',
                               'prereq': []},
    'Shield_ShieldWall': {   'attr': 'Willpower',
                             'cost': 200,
                             'min': 25,
                             'name': 'Shield Wall',
                             'parent': 'Shield',
                             'prereq': []},
    'Shield_Slam': {   'attr': 'Strength',
                       'cost': 100,
                       'min': 17,
                       'name': 'Shield Slam',
                       'parent': 'Shield',
                       'prereq': []},
    'Shield_StaggeringBlock': {   'attr': 'Strength',
                                  'cost': 200,
                                  'min': 21,
                                  'name': 'Staggering Block',
                                  'parent': 'Shield',
                                  'prereq': []},
    'Shield_SwiftBlocking': {   'attr': 'Agility',
                                'cost': 200,
                                'min': 19,
                                'name': 'Swift Blocking',
                                'parent': 'Shield',
                                'prereq': []},
    'ShortBlades': {   'attr': 'Agility',
                       'cost': 50,
                       'min': 0,
                       'name': 'Short Blade',
                       'parent': None,
                       'prereq': []},
    'ShortBlades_Bloodletter': {   'attr': 'Agility',
                                   'cost': 150,
                                   'min': 17,
                                   'name': 'Bloodletter',
                                   'parent': 'ShortBlades',
                                   'prereq': []},
    'ShortBlades_Expertise': {   'attr': 'Agility',
                                 'cost': 0,
                                 'min': 0,
                                 'name': 'Short Blade Expertise',
                                 'parent': 'ShortBlades',
                                 'prereq': []},
    'ShortBlades_Hobble': {   'attr': 'Agility',
                              'cost': 150,
                              'min': 21,
                              'name': 'Hobble',
                              'parent': 'ShortBlades',
                              'prereq': []},
    'ShortBlades_Jab': {   'attr': 'Agility',
                           'cost': 100,
                           'min': 17,
                           'name': 'Jab',
                           'parent': 'ShortBlades',
                           'prereq': []},
    'ShortBlades_PointedCircle': {   'attr': 'Agility',
                                     'cost': 100,
                                     'min': 23,
                                     'name': 'Pointed Circle',
                                     'parent': 'ShortBlades',
                                     'prereq': ['Tactics_Juke']},
    'ShortBlades_Rejoinder': {   'attr': 'Agility',
                                 'cost': 250,
                                 'min': 25,
                                 'name': 'Rejoinder',
                                 'parent': 'ShortBlades',
                                 'prereq': []},
    'ShortBlades_Shank': {   'attr': 'Agility',
                             'cost': 250,
                             'min': 27,
                             'name': 'Shank',
                             'parent': 'ShortBlades',
                             'prereq': []},
    'SingleWeaponFighting': {   'attr': 'Agility|Strength',
                                'cost': 100,
                                'min': 0,
                                'name': 'Single Weapon Fighting',
                                'parent': None,
                                'prereq': []},
    'SingleWeaponFighting_OpportuneAttacks': {   'attr': 'Agility|Strength',
                                                 'cost': 0,
                                                 'min': 17,
                                                 'name': 'Opportune Attacks',
                                                 'parent': 'SingleWeaponFighting',
                                                 'prereq': []},
    'SingleWeaponFighting_PenetratingStrikes': {   'attr': 'Agility|Strength',
                                                   'cost': 200,
                                                   'min': 23,
                                                   'name': 'Penetrating '
                                                           'Strikes',
                                                   'parent': 'SingleWeaponFighting',
                                                   'prereq': []},
    'SingleWeaponFighting_WeaponExpertise': {   'attr': 'Agility|Strength',
                                                'cost': 150,
                                                'min': 21,
                                                'name': 'Weapon Expertise',
                                                'parent': 'SingleWeaponFighting',
                                                'prereq': []},
    'SingleWeaponFighting_WeaponMastery': {   'attr': 'Agility|Strength',
                                              'cost': 300,
                                              'min': 29,
                                              'name': 'Weapon Mastery',
                                              'parent': 'SingleWeaponFighting',
                                              'prereq': [   'SingleWeaponFighting_WeaponExpertise']},
    'Survival': {   'attr': 'Intelligence',
                    'cost': 100,
                    'min': 0,
                    'name': 'Wayfaring',
                    'parent': None,
                    'prereq': []},
    'Survival_Camp': {   'attr': 'Intelligence',
                         'cost': 0,
                         'min': 15,
                         'name': 'Make Camp',
                         'parent': 'Survival',
                         'prereq': []},
    'Survival_DesertCanyonSurvival': {   'attr': 'Intelligence',
                                         'cost': 50,
                                         'min': 17,
                                         'name': 'Wilderness Lore: Canyons',
                                         'parent': 'Survival',
                                         'prereq': []},
    'Survival_JungleSurvival': {   'attr': 'Intelligence',
                                   'cost': 50,
                                   'min': 19,
                                   'name': 'Wilderness Lore: Jungles',
                                   'parent': 'Survival',
                                   'prereq': []},
    'Survival_MountainsSurvival': {   'attr': 'Intelligence',
                                      'cost': 50,
                                      'min': 17,
                                      'name': 'Wilderness Lore: Hills and '
                                              'Mountains',
                                      'parent': 'Survival',
                                      'prereq': []},
    'Survival_PlainsSurvival': {   'attr': 'Intelligence',
                                   'cost': 25,
                                   'min': 15,
                                   'name': 'Wilderness Lore: Flower Fields',
                                   'parent': 'Survival',
                                   'prereq': []},
    'Survival_RiversLakesSurvival': {   'attr': 'Intelligence',
                                        'cost': 50,
                                        'min': 19,
                                        'name': 'Wilderness Lore: Rivers and '
                                                'Lakes',
                                        'parent': 'Survival',
                                        'prereq': []},
    'Survival_RuinsSurvival': {   'attr': 'Intelligence',
                                  'cost': 50,
                                  'min': 21,
                                  'name': 'Wilderness Lore: Ruins',
                                  'parent': 'Survival',
                                  'prereq': []},
    'Survival_SaltDesertSurvival': {   'attr': 'Intelligence',
                                       'cost': 50,
                                       'min': 19,
                                       'name': 'Wilderness Lore: Salt Dunes',
                                       'parent': 'Survival',
                                       'prereq': []},
    'Survival_SaltmarshSurvival': {   'attr': 'Intelligence',
                                      'cost': 50,
                                      'min': 15,
                                      'name': 'Wilderness Lore: Marshes',
                                      'parent': 'Survival',
                                      'prereq': []},
    'Survival_Trailblazer': {   'attr': 'Intelligence',
                                'cost': 0,
                                'min': 15,
                                'name': "Mind's Compass",
                                'parent': 'Survival',
                                'prereq': []},
    'Tactics': {   'attr': 'Agility',
                   'cost': 50,
                   'min': 0,
                   'name': 'Tactics',
                   'parent': None,
                   'prereq': []},
    'Tactics_Charge': {   'attr': 'Strength',
                          'cost': 150,
                          'min': 17,
                          'name': 'Charge',
                          'parent': 'Tactics',
                          'prereq': []},
    'Tactics_Hurdle': {   'attr': 'Agility',
                          'cost': 0,
                          'min': 0,
                          'name': 'Hurdle',
                          'parent': 'Tactics',
                          'prereq': []},
    'Tactics_Juke': {   'attr': 'Agility',
                        'cost': 200,
                        'min': 21,
                        'name': 'Juke',
                        'parent': 'Tactics',
                        'prereq': []},
    'Tactics_Kickback': {   'attr': 'Strength',
                            'cost': 50,
                            'min': 19,
                            'name': 'Kickback',
                            'parent': 'Tactics',
                            'prereq': []},
    'Tactics_Throwing': {   'attr': 'Agility',
                            'cost': 50,
                            'min': 10,
                            'name': 'Deft Throwing',
                            'parent': 'Tactics',
                            'prereq': []},
    'Tinkering': {   'attr': 'Intelligence',
                     'cost': 100,
                     'min': 0,
                     'name': 'Tinkering',
                     'parent': None,
                     'prereq': []},
    'Tinkering_DeployTurret': {   'attr': 'Intelligence',
                                  'cost': 100,
                                  'min': 17,
                                  'name': 'Deploy Turret',
                                  'parent': 'Tinkering',
                                  'prereq': []},
    'Tinkering_Disassemble': {   'attr': 'Intelligence',
                                 'cost': 100,
                                 'min': 15,
                                 'name': 'Disassemble',
                                 'parent': 'Tinkering',
                                 'prereq': []},
    'Tinkering_GadgetInspector': {   'attr': 'Intelligence',
                                     'cost': 0,
                                     'min': 15,
                                     'name': 'Gadget Inspector',
                                     'parent': 'Tinkering',
                                     'prereq': []},
    'Tinkering_LayMine': {   'attr': 'Intelligence',
                             'cost': 50,
                             'min': 17,
                             'name': 'Lay Mine / Set Bomb',
                             'parent': 'Tinkering',
                             'prereq': []},
    'Tinkering_Repair': {   'attr': 'Intelligence',
                            'cost': 100,
                            'min': 17,
                            'name': 'Repair',
                            'parent': 'Tinkering',
                            'prereq': []},
    'Tinkering_ReverseEngineer': {   'attr': 'Intelligence',
                                     'cost': 100,
                                     'min': 25,
                                     'name': 'Reverse Engineer',
                                     'parent': 'Tinkering',
                                     'prereq': ['Tinkering_Disassemble']},
    'Tinkering_Scavenger': {   'attr': 'Intelligence',
                               'cost': 100,
                               'min': 15,
                               'name': 'Scavenger',
                               'parent': 'Tinkering',
                               'prereq': []},
    'Tinkering_Tinker1': {   'attr': 'Intelligence',
                             'cost': 100,
                             'min': 19,
                             'name': 'Tinker I',
                             'parent': 'Tinkering',
                             'prereq': []},
    'Tinkering_Tinker2': {   'attr': 'Intelligence',
                             'cost': 200,
                             'min': 23,
                             'name': 'Tinker II',
                             'parent': 'Tinkering',
                             'prereq': ['Tinkering_Tinker1']},
    'Tinkering_Tinker3': {   'attr': 'Intelligence',
                             'cost': 300,
                             'min': 29,
                             'name': 'Tinker III',
                             'parent': 'Tinkering',
                             'prereq': ['Tinkering_Tinker2']}}


def get_skill_info(skill_class):
    """Case-insensitive lookup in SKILL_DATABASE."""
    if not skill_class:
        return None
    if skill_class in SKILL_DATABASE:
        return SKILL_DATABASE[skill_class]
    sc_lower = skill_class.lower()
    for k, v in SKILL_DATABASE.items():
        if k.lower() == sc_lower or v.get("name", "").lower() == sc_lower:
            return v
    return None


def is_skill_learnable(skill_class, learned_skills, current_stats, sp, learnable_telem=None):
    """
    Determines if skill_class can be learned right now.
    Returns: (can_learn: bool, reason: str, cost: int)
    """
    info = get_skill_info(skill_class)
    if not info:
        return False, f"Unknown skill {skill_class}", 0

    cost = info.get("cost", 0)
    learned_lower = {s.lower() for s in learned_skills}
    if skill_class.lower() in learned_lower or info.get("name", "").lower() in learned_lower:
        return False, f"Already learned {skill_class}", 0

    # 1. If engine telemetry provided, verify against learnable_skills
    if learnable_telem is not None:
        telem_classes = {item.get("class", "").lower(): item for item in learnable_telem}
        telem_names = {item.get("name", "").lower(): item for item in learnable_telem}
        match = telem_classes.get(skill_class.lower()) or telem_names.get(info.get("name", "").lower())
        if match:
            return True, "Eligible via engine verification", match.get("cost", cost)
        # If not in telemetry, determine why
        if sp < cost:
            return False, f"Insufficient SP (Have {sp}, need {cost})", cost
        parent = info.get("parent")
        if parent and parent.lower() not in learned_lower:
            return False, f"Missing parent skill {parent}", cost
        for pr in info.get("prereq", []):
            if pr.lower() not in learned_lower:
                return False, f"Missing prerequisite power {pr}", cost
        attr = info.get("attr", "")
        min_stat = info.get("min", 0)
        if attr and min_stat > 0:
            attrs_to_check = [a.strip() for a in attr.replace("|", ",").split(",") if a.strip()]
            if not any(current_stats.get(a, 10) >= min_stat for a in attrs_to_check):
                return False, f"Insufficient {attr} (Need {min_stat})", cost
        return False, f"Skill {skill_class} not learnable via engine requirements", cost

    # 2. Offline / Mock evaluation using SKILL_DATABASE
    parent = info.get("parent")
    if parent and parent.lower() not in learned_lower:
        return False, f"Missing parent skill {parent}", cost

    for pr in info.get("prereq", []):
        if pr.lower() not in learned_lower:
            return False, f"Missing prerequisite power {pr}", cost

    attr = info.get("attr", "")
    min_stat = info.get("min", 0)
    if attr and min_stat > 0:
        attrs_to_check = [a.strip() for a in attr.replace("|", ",").split(",") if a.strip()]
        if not any(current_stats.get(a, 10) >= min_stat for a in attrs_to_check):
            return False, f"Insufficient {attr} (Need {min_stat})", cost

    if sp < cost:
        return False, f"Insufficient SP (Have {sp}, need {cost})", cost

    return True, "Requirements met", cost


def get_best_skill_to_learn(game_state, template):
    """
    Selects the optimal skill or power to learn according to archetype doctrine.
    1. Instant claim of ready 0-cost powers whose parent/prereqs are met.
    2. In-order evaluation of archetype skill_progression.
    3. If next priority skill requires more SP than currently held, signals
       to save SP (is_saving=True) to prevent wasting points on filler.
    Returns: (skill_class: str or None, reason: str, is_saving: bool)
    """
    sp = game_state.get("sp", 0)
    learned = set(game_state.get("skills", []))
    learned_lower = {s.lower() for s in learned}
    attrs = game_state.get("attributes", {})
    learnable_telem = game_state.get("learnable_skills", None)
    progression = template.get("skill_progression", [])

    # Priority 1: Instant claim of free (0-cost) powers whose requirements are met!
    for cand in progression:
        info = get_skill_info(cand)
        cand_name = info.get("name", "") if info else ""
        if cand.lower() in learned_lower or (cand_name and cand_name.lower() in learned_lower):
            continue
        can_learn, reason, cost = is_skill_learnable(cand, learned, attrs, sp, learnable_telem)
        if can_learn and cost == 0:
            return cand, f"Class Progression ({template.get('name', 'Class')}): Claiming free power {cand} (0 SP)", False

    # Priority 2: In-order progression through archetype doctrine
    for cand in progression:
        info = get_skill_info(cand)
        cand_name = info.get("name", "") if info else ""
        if cand.lower() in learned_lower or (cand_name and cand_name.lower() in learned_lower):
            continue
        can_learn, reason, cost = is_skill_learnable(cand, learned, attrs, sp, learnable_telem)
        if can_learn:
            return cand, f"Class Progression ({template.get('name', 'Class')}): Unlocking priority skill {cand} (Cost: {cost} SP)", False
        else:
            # If insufficient SP, signal to SAVE SP for this priority skill!
            if "Insufficient SP" in reason:
                return None, f"Class Progression ({template.get('name', 'Class')}): Saving SP for priority skill {cand} (Have {sp}, need {cost})", True
            # If missing parent skill, check if parent is learnable
            parent = info.get("parent") if info else None
            if parent and parent.lower() not in learned_lower:
                can_p, p_reason, p_cost = is_skill_learnable(parent, learned, attrs, sp, learnable_telem)
                if can_p:
                    return parent, f"Class Progression ({template.get('name', 'Class')}): Unlocking parent skill {parent} for {cand} (Cost: {p_cost} SP)", False
                elif "Insufficient SP" in p_reason:
                    return None, f"Class Progression ({template.get('name', 'Class')}): Saving SP for parent skill {parent} (Have {sp}, need {p_cost})", True

    return None, "No eligible skills to learn in progression", False
